export interface IHouse {
  ID: number
  Entrancex: number
  Entrancey: number
  Entrancez: number
  Exitx: number
  Exity: number
  Exitz: number
  Owner: string
  Discription: string
  Value: number
  Hel: number
  Arm: number
  Music: number
  Interior: number
  InteriorType: number
  Lockk: number
  Owned: number
  Rent: number
  Rentabil: number
  Takings: number
  Level: number
  Virtual: number
  Prices: number
  garaj: number
  gSlot: number
  gAngel: number
  gExtX: number
  gExtY: number
  gExtZ: number
}
