import { IClan } from "features/clans/interfaces"

export interface IUser {
  Level: number
  Bank: number
  Money: number
  id: number
  name: string
  password: string
  Security: string
  IP: string
  Admin: number
  Helper: number
  Premium: number
  PremiumPoints: number
  ConnectedTime: number
  Registered: number
  Sex: number
  Age: number
  Muted: number
  MuteTime: number
  Respect: number
  Crimes: number
  Kills: number
  Deaths: number
  Arrested: number
  WantedDeaths: number
  Phonebook: number
  LottoNr: number
  WantedLevel: number
  Job: number
  Paycheck: number
  Jailed: number
  JailTime: number
  Materials: number
  Drugs: number
  Leader: number
  Member: number
  Rank: number
  CChar: number
  FWarn: number
  FPunish: number
  Acceptpoints: number
  Team: number
  Model: number
  PhoneNr: number
  PhoneCredits: number
  House: number
  Bizz: number
  Rob: number
  CarLicT: number
  CarLic: number
  FlyLicT: number
  FlyLic: number
  BoatLicT: number
  BoatLic: number
  FishLicT: number
  FishLic: number
  GunLicT: number
  GunLic: number
  PayDay: number
  PayDayHad: number
  Tutorial: number
  Warnings: number
  Rented: number
  Fuel: number
  WTalkie: number
  Lighter: number
  Cigarettes: number
  Tow: number
  Email: string
  RegisterDate: string
  lastOn: string
  Banned: number
  Victim: string
  Radio2: number
  Status: number
  CRank: number
  Phone: number
  Accused: string
  Crime1: string
  Crime2: string
  Crime3: string
  BTemp: number
  BYear: number
  BMonth: number
  BDay: number
  BBy: string
  BReason: string
  ALeader: number
  HPoints: number
  TruckerSkill: number
  GarbageSkill: number
  ShowJob: number
  ShowFP: number
  ShowLogo: number
  ShowCeas: number
  MowerSkill: number
  Clan: number
  ClanRank: number
  Pin: number
  Seconds: number
  Commands: number
  Commands2: number
  Commands3: number
  Commands4: number
  Commands5: number
  ShowFaction: number
  GiftPoints: number
  NewbieMute: number
  HelpedPlayers: number
  SpawnChange: number
  DailyMission: number
  DailyMission2: number
  Progress: number
  Progress2: number
  NeedProgress1: number
  NeedProgress2: number
  Youtuber: number
  IceSkill: number
  ReportTime: number
  EvSeconds: number
  Descalificat: string
  WTChannel: number
  PizzaSkill: number
  GasCan: number
  CurierSkill: number
  ShowGlasses: number
  Glasses: number
  HelpedPlayersToday: number
  Used: number
  Days: number
  FarmerSkill: number
  PilotSkill: number
  ShowHP: number
  ShowAP: number
  Color: number
  Kicks: number
  Warns: number
  Bans: number
  Jails: number
  Mutes: number
  HoursMonth: number
  DayHours: number
  Slot1: number
  Slot2: number
  Slot3: number
  Slot4: number
  Slot5: number
  Vip: number
  Mats: number
  ClanWarns: number
  ClanDays: number
  CarLicS: number
  FlyLicS: number
  BoatLicS: number
  GunLicS: number
  FishSkill: number
  ShowDMG: number
  EscapePoints: number
  AJail: number
  Hat: number
  ShowHat: number
  NewbieChat: number
  TogLC: number
  TogFC: number
  TogWT: number
  HidePM: number
  TogNews: number
  TogLicitatie: number
  TogClan: number
  TogEvent: number
  TogDing: number
  PhoneOnline: number
  DayLogin: number
  AW: number
  HW: number
  LW: number
  Tag: number
  MatSkill: number
  PaintKills1: number
  PaintKills2: number
  PaintKills3: number
  PaintDeaths1: number
  PaintDeaths2: number
  PaintDeaths3: number
  RacePoints: number
  RacePlace1: number
  RacePlace2: number
  RacePlace3: number
  RacePlace4: number
  ArenaKills: number
  ArenaDeaths: number
  Crash: number
  PosX: number
  PosY: number
  PosZ: number
  InvalidCommands: number
  Referral: number
  ReferralMoney: number
  ReferralRP: number
  SpecialQuest: string
  Coins: number
  StivuitorSkill: number
  DM: number
  Propose: string
  WarKills: number
  WarDeaths: number
  WarTurf: number
  TogVip: number
  Fires: number
  TogSurf: number
  TogFind: number
  TogRaport: number
  TogJob: number
  TogAlert: number
  TogDice: number
  ShowCP: number
  AchievementStatus: string
  WantedTime: number
  ShowProgress1: number
  ShowProgress2: number
  DailyLogin: number
  Backpack: number
  NewsPaperSkill: number
  DailyBonus: number
  IceQuest: number
  OnlineLastWeek: number
  HeadValue: number
  MechSkill: number
  DrugsSkill: number
  RobSkill: number
  pHealth: number
  Inter: number
  Local: number
  LawSkill: number
  GotCode: number
  Refund: number
  FightStyle: number
  Firework: number
  ReAp: number
  ToySlot: number
  GangPoints: number
  FacingAngle: number
  Newbie: number
  JobBonus50: number
  JobBonus100: number
  Seeds: string
  DanhHieuActive: string
  DanhHieu: string
  Matuy1: number
  Matuy2: number
  Seed1: number
  Seed2: number
  ActivePoints: number
  SoMayMan: string
  DailyMission3: number
  Progress3: number
  NeedProgress3: number
  Skin: string
  Crates: string
  TimeTrongNgay: number
  DiemDanh: number
  NgayDiemDanh: number
  NhanThuongDiemDanh: string
  CasinoChip: number
  CarKey1: number
  CarKey2: number
  CarKey3: number
  CarKey4: number
  CarKey5: number
  CarKey6: number
  CarKey7: number
  CarKey8: number
  CarKey9: number
  CarKey10: number
  RewardTime: number
  clan: IClan
}
