export interface IVehicle {
  ID: number
  Model: number
  Locationx: number
  Locationy: number
  Locationz: number
  Angle: number
  ColorOne: number
  ColorTwo: number
  Owner: string
  Value: number
  License: string
  Alarm: number
  Lockk: number
  mod0: number
  mod1: number
  mod2: number
  mod3: number
  mod4: number
  mod5: number
  mod6: number
  mod7: number
  mod8: number
  mod9: number
  mod10: number
  mod11: number
  mod12: number
  mod13: number
  paintjob: number
  KM: number
  Userid: number
  Confiscated: number
  Spawned: number
  Special: number
  Points: number
  Tax: number
  Fuel: number
  Neon: number
  Text: string
  ColorText: number
  Level: number
}
